version: '3.8'

services:
  converter-bot:
    build: .
    container_name: mirocopy-converterbot
    restart: always
    volumes:
      - ./resources:/app/resources
      - /var/run/docker.sock:/var/run/docker.sock
